name: Sync to Gitee

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Sync to Gitee
      uses: mirrorhubio/gitee-sync@v2
      with:
        source_repo: ${{ github.repository }}
        source_branch: ${{ github.ref }}
        target_repo: primihub/primihub-docs
        target_branch: main
        gitee_token: ${{ secrets.GITEE_TOKEN }}